### Read all films
GET http://localhost:3000/films


### read filtered films
GET http://localhost:3000/films/?minimum-duration=122

@baseUrl = http://localhost:3000

### Read film identified by 2
GET {{baseUrl}}/films/2

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Weathering with you",
    "director":"Makoto Shinkai",
    "duration":114
}

### Create another film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Oppenheimer",
    "director":"Christopher Nolan",
    "duration":180,
    "budget":100,
    "description":"atomic bomb"
}

### Delete a film
DELETE {{baseUrl}}/films/8

### Update the film identified by 5
PATCH {{baseUrl}}/films/5
Content-Type: application/json

{
    "description":"bombastic"
}

### create a film with put
PUT {{baseUrl}}/films/7
Content-Type: application/json

{
    "title":"Le Comte de Monte-Cristo",
    "director":"Alexandre de La Patellière et Matthieu Delaporte",
    "duration":178,
    "description":"vengeance hehe"
}

### modify a film with put
PUT {{baseUrl}}/films/7
Content-Type: application/json

{
    "title":"Barbie",
    "director":"Greta Gerwig",
    "duration":114,
    "description":"serious"
}


### Create a film by using the admin account
#### First login as the admin
##### Define a request variable named admin :
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

#### Create a film with the admin token
POST {{baseUrl}}/films
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "title":"The Matrix",
    "director":"Lana Wachowski",
    "duration":136    
}
